services:
  # Web service for the admin dashboard
  - type: web
    name: skyhustle-dashboard
    env: python
    plan: free
    buildCommand: pip install -r deploy-requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BASE64_CREDS
        sync: false
      - key: SHEET_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true

  # Worker service for the Telegram bot (runs continuously)
  - type: worker
    name: skyhustle-bot
    env: python
    plan: free
    buildCommand: pip install -r deploy-requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BASE64_CREDS
        sync: false
      - key: SHEET_ID
        sync: false
      - key: SESSION_SECRET
        sync: false
      - fromService:
          name: skyhustle-dashboard
          type: web
          envVarKey: SESSION_SECRET
    autoDeploy: true