services:
  - type: web
    name: skyhustle-bot
    env: node
    plan: starter
    region: frankfurt       # or your preferred region
    branch: main
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm run start 