services:
  - type: web
    name: skyhustle
    env: node
    # … rest of your config …

    envVars:
      # A non-secret you’re happy committing
      - key: NODE_ENV
        value: production

      # Secrets managed exclusively via the Render dashboard
      - key: BOT_TOKEN
        sync: true
      - key: BASE64_CREDS
        sync: true
      - key: SHEET_ID
        sync: true
version: "1"
