services:
  - type: web
    name: skyhustle
    env: node
    repo: https://github.com/yanny526/SkyHustle
    branch: main
    plan: starter
    region: oregon       # or your preferred region
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
version: "1"
